### ISSUE TITLE
file_browser_callback on tinymce_options

### ISSUE THREAD

**Issue by jordanraji** [azsoftware/wtf_tinymce#1]
Hi, I want to use `file_browser_callback`  [(TinyMCE docs)](https://www.tinymce.com/docs/configure/file-image-upload/#automatic_uploads).

I tried this:
`
text = TinyMceField(
        'Text',
        tinymce_options={
            'file_browser_callback': "function(field_name, url, type, win) {win.document.getElementById(field_name).value = 'my browser value';}",
            'file_browser_callback_types': 'file image media'
            }
    )
`

JS code is not recognized. Help!

**Comment by azsoftware** [comment]
Fixed with version 0.1.3 https://pypi.python.org/pypi/wtf-tinymce/0.1.3
